apiVersion: batch/v1beta1  #API group is batch, version is v1beta1
kind: CronJob 
metadata:
  name: batch-job-every-fifteen-minutes 
  spec:
  schedule: "0,15,30,45 * * * *" #this job should run at the 0, 15, 30 and 45 minutes of every hour, every day 
  jobsTemplate:
    spec:
      template: #The template for the Job Resource that will be created by this CronJob
        metadata:
          labels:
            app: periodic-batch-job 
        spec:
          restartPolicy: OnFailure 
          containers:
          - name: main 
            image: luksa/batch-job 
