apiVersion: v1
kind: Service 
metadata:
  name: kubia 
spec:
  ports:
  - port: 80 #the port this service will be available on 
    targetPort: 8080 #the container port the service will forward to
  selector: #all pods with the app=kubia label will be part of this service
    app: kubia