apiVersion: apps/v1beta2 
kind: ReplicaSet
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    matchExpressions: #this selector requires the pod to contain a label with the "app" key 
      - key: app
        operator: In 
        values:  #the label's value must be "kubia"
          - kubia  
  template: #the pod template for creating new pods 
    metadata:
      labels:
        app: kubia 
    spec:
      containers:
      - name: kubia
        image: luksa/kubia #replace the image 
        #ports:
        #- containerPort: 8080
