apiVersion: v1
kind: ReplicationController 
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    app: kubia 
template: #the pod template for creating new pods 
  metadata:
    labels:
      app: kubia 
  spec:
    containers:
    - name: kubia
      image: luksa/kubia #replace the image 
      ports:
      - containerPort: 8080
