apiVersion: batch/v1 
kind: Job 
metadata:
  name: multi-completion-batch-job 
spec:
  completions: 5 #this job must ensure FIVE pods complete successfully 
  parallelism: 2 #up to two pods can run in parallel 
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure #Jobs can't use the default restart policy, which is ALWAYS  
      containers:
      - name: main 
        image: luksa/batch-job 