apiVersion: v1
kind: Pod 
metadata: 
    name: kubia-with-multiple-ports
spec:
  containers:
    - name: kubia 
      ports:
      - name: http #its name to refer
        containerPort: 8080 
      - name: https #its name to refer
        containerPort: 8443 